### ISSUE TITLE
🚀 - console.log

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [riccardoperra/codeimage#309]
### Description

Could you show the result in grey of the Console.log()

console.log(3) /// 3

**Comment by riccardoperra** [comment]
Hi @jojojojojoj5564656465465 , this could be a great feature but doing that right now requires a lot of efforts and it could change the way CodeImage take. 

Also, I don't know if it's possible doing something like that since there are a lot of variables behind this implementation, for example:
- what if I do a console.log() using an invalid parameter or non-constant? I may have to execute the code do to that.
- what if I place a function and never execute it?
- a lot more.. 

I mean, currently there is no any type of "playground" / live code execution implementation.

If you have any suggestion about an implementation using CM6 or if you have a working example, I may focus on studying some CodeMirror internals to try do to that. 

Thank you 😊

**Comment by jojojojojoj5564656465465** [comment]
Maybe show as background wallpapers the result of it even if it's not super clear

**Comment by riccardoperra** [comment]
It doesn't change 😅 

Example async function

```typescript
async function foo(parameter) {
  const result = await fetch('...).then(res => res.json());
  console.log(result);
  console.log(parameter);
}
```

On a code like that, I should find first the function `foo`, then I have to evaluate it. So there will be an http call. How could I be able to get the result or the `parameter` variable?

Doing that manually, for example adding a placeholder with // since there is the highlighting available is just ok

```typescript
async function foo() {
  console.log(result); // 3
}
```
