### ISSUE TITLE
🐞 - When choosing Background: None, it switches back to Bottom

### ISSUE THREAD

**Issue by Gw3i** [riccardoperra/codeimage#420]
### Which @codeimage/* package(s) are the source of the bug?

Don't known / other

### Description

You can't select Background: None. It automatically switches back to Background: Bottom

<img width="330" alt="Screenshot 2022-12-16 at 10 52 22" src="https://user-images.githubusercontent.com/101993818/208072142-3f93be37-4d51-446a-9304-097d9dd63a4f.png">
<img width="316" alt="Screenshot 2022-12-16 at 10 52 28" src="https://user-images.githubusercontent.com/101993818/208072155-d96379f7-d142-4044-b6b1-2ae1738e723e.png">

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by riccardoperra** [comment]
Hi @Gw3i, thanks to reaching me.

this is definitely a bug caused of this portion of code I think

https://github.com/riccardoperra/codeimage/blob/d3c3293837a87cd9238382f056a83b82908276c6/apps/codeimage/src/components/PropertyEditor/WindowStyleForm.tsx#L157

The ?? check should be removed since “None” options is valuated with null.

In case you can open a PR, otherwise I will resolve it soon (probably today or tomorrow)

thanks again 😬

**Comment by riccardoperra** [comment]
Deployed the fix with [1.0.7](https://github.com/riccardoperra/codeimage/releases/tag/v1.0.7) release 😄 thanks for submitting the issue
