### ISSUE TITLE
🚀 - GitHub Dark Dimmed Theme

### ISSUE THREAD

**Issue by JustDesoroxxx** [riccardoperra/codeimage#449]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

highlight

### Description

Currently only GitHub Dark theme is available, it would be perfect if GitHub Dark Dimmed was available!

**Comment by riccardoperra** [comment]
I will work on it this weekend 😄 Thanks

**Comment by riccardoperra** [comment]
Hey @JustDesoroxxx, I just added a preview for the github dark dimmed theme here https://codeimage-app-pr-450.vercel.app/ with #450 pr. If something is missing in your opinion just telI me, I will deploy it once is ok

**Comment by JustDesoroxxx** [comment]
There is just a little problem that you can see here:

![image](https://user-images.githubusercontent.com/82710983/215294925-bd15bb1f-b6bc-4bc1-8c22-e32340cb46ab.png)

![image](https://user-images.githubusercontent.com/82710983/215294988-8ace3416-eda1-4243-b831-868adea9ffdf.png)

Other than that, looks awesome!

**Comment by riccardoperra** [comment]
I've updated the variable and token colors, but for now I want to differentiate the type keyword
![image](https://user-images.githubusercontent.com/37072694/215335792-9903078f-99d3-4fce-ac73-bb71d60d810b.png)

Also, the "void" is considered a keyword by [the java lezer parser ](https://github.com/lezer-parser/java/blob/main/src/highlight.js) so the color will not change at the moment

**Comment by riccardoperra** [comment]
I've updated the variable and token colors, but for now I want to differentiate the type keyword
![image](https://user-images.githubusercontent.com/37072694/215335792-9903078f-99d3-4fce-ac73-bb71d60d810b.png)

Also, **void** is considered a keyword by [the java lezer parser ](https://github.com/lezer-parser/java/blob/main/src/highlight.js) so the color will not change at the moment.

I've also found that I currently have no way to differentiate properties from function methods

I need to figure out in the future how to extend the parser to handle more cases. Now I prefer to leave it as it is. probably these problems are solved if i add the textmate grammar instead of lezer, but don't know if it's supported
