### ISSUE TITLE
🚀 - Support more languages like "shell"

### ISSUE THREAD

**Issue by PeterDaveHello** [riccardoperra/codeimage#454]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

codeimage

### Description

Would be great to see more language to be supported to have beautiful syntax highlight here 🎉

**Comment by riccardoperra** [comment]
Hey @PeterDaveHello, since I'm using codemirror6 I don't have the full language support like the previous version.

Here's the list of the legacy languages which I can add to CodeImage
https://github.com/codemirror/legacy-modes

In case, shell is present so I will add it soon, but in case do you also need some other language present on the page?

**Comment by PeterDaveHello** [comment]
Hi @riccardoperra, thanks for your prompt reply, currently, shell is the only language I'd like to have its support, but please feel free to take your time :D

**Comment by riccardoperra** [comment]
No worries it's just a configuration 😄 he https://github.com/riccardoperra/codeimage/pull/455

**Comment by riccardoperra** [comment]
Deployed with [v1.1.4](https://github.com/riccardoperra/codeimage/releases/tag/v1.1.4) release - https://github.com/riccardoperra/codeimage/actions/runs/4047006131

**Comment by PeterDaveHello** [comment]
Good to see that Dockerfile is also supported! Thank you @riccardoperra!
