### ISSUE TITLE
🚀 - Let user change syntax highlighting without changing the background

### ISSUE THREAD

**Issue by goncy** [riccardoperra/codeimage#470]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

codeimage

### Description

I was trying to see which syntax matched better with the background I selected by everytime I changed the theme the background changed too

**Comment by hackpirodev** [comment]
Thanks for the suggestion, @goncy. I believe we can address this in issue #472 (https://github.com/riccardoperra/codeimage/issues/472), feel free to comment with any suggestions. @riccardoperra, what are your thoughts on decoupling syntax highlighting from the theme to allow users to customize the left sidebar with default themes? However, we should also consider what happens when a user changes settings and how it affects the selected theme.

One solution could be to display an input field with a placeholder for the theme name and a 'save' button in the right sidebar when the user modifies the selected theme. This way, users can easily switch between themes and customize their left sidebar. Other suggestions?

**Comment by goncy** [comment]
What I feel is weird is that `theme` refers to Syntax Highlighting + Background, and you can change the Background independently but not Syntax Highlighting. I think it would be nice to have a `theme` as an overall thing. My theme being *all* the configurations. So I can have one for my React snippets, one for my Vue snippets, and so on.

Or to have a dropdown for syntax highlighting, and that's it. I think both are ok.

**Comment by riccardoperra** [comment]
As @hackpirodev mentioned, we are starting to work on a preset feature that will allow you to save settings and reuse them whenever you want, a bit like templates.

Since it's just started I expect it will probably be completed by the end of March, so we can start separating the various inputs, and allow you to lock the background if you try to change the theme

**Comment by riccardoperra** [comment]
At the moment we introduced a dedicated input with [1.2.0](https://github.com/riccardoperra/codeimage/releases/tag/v1.2.0)
