### ISSUE TITLE
🤖 - How to configure AUTH0_CLIENT_CLAIMS

### ISSUE THREAD

**Issue by ccbikai** [riccardoperra/codeimage#654]
### Description

I have deployed codeimage locally, and I can get the req.user information.

<img width="859" alt="Cursor 2024-11-17 14 11 07" src="https://github.com/user-attachments/assets/522a9a36-0e74-4176-9c4e-1981893ae7d6">

However, there is no email field inside, and AUTH0_CLIENT_CLAIMS must be configured as a URL

<img width="517" alt="Cursor 2024-11-17 14 11 44" src="https://github.com/user-attachments/assets/ae94ad27-d2d8-4e79-a372-95cb23262238">

I would like to ask how to configure AUTH0_CLIENT_CLAIMS in order to obtain the Email (the local localstorage user information contains Email)

**Comment by riccardoperra** [comment]
Hi, in order to run codeimage locally with authentication enabled you need to provide your own auth0 configuration, which could be a little tricky.

The env var you mentioned is linked in the prod environment with the url of the website. There is a Auth0 automated flow that augment the jwt token adding a email claim.
